/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.colegio.hospitalinformatica.view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        
        ImageIcon icone = new ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/icone.png"));
        this.setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        mnbPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mniNovoPaciente = new javax.swing.JMenuItem();
        mniNovoMedico = new javax.swing.JMenuItem();
        mniNovaConsulta = new javax.swing.JMenuItem();
        mniSair = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mniPacientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mniSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Informática");

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("HOSPITAL");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        mnbPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mnArquivo.setText("Arquivo");

        mniNovoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/paciente.png"))); // NOI18N
        mniNovoPaciente.setText("Novo Paciente");
        mniNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoPacienteActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovoPaciente);

        mniNovoMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/medico.png"))); // NOI18N
        mniNovoMedico.setText("Novo Médico");
        mniNovoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoMedicoActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovoMedico);

        mniNovaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/plus.png"))); // NOI18N
        mniNovaConsulta.setText("Nova Consulta");
        mniNovaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovaConsultaActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovaConsulta);

        mniSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/exit.png"))); // NOI18N
        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnArquivo.add(mniSair);

        mnbPrincipal.add(mnArquivo);

        mnRelatorio.setText("Relatórios");

        mniPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/pacientes_cadastrados.png"))); // NOI18N
        mniPacientes.setText("Pacientes");
        mniPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPacientesActionPerformed(evt);
            }
        });
        mnRelatorio.add(mniPacientes);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/medicos_cadastrados.png"))); // NOI18N
        jMenuItem1.setText("Médicos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnRelatorio.add(jMenuItem1);

        mnbPrincipal.add(mnRelatorio);

        mnAjuda.setText("Ajuda");

        mniSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/colegio/hospitalinformatica/imagens/information.png"))); // NOI18N
        mniSobre.setText("Sobre");
        mnAjuda.add(mniSobre);

        mnbPrincipal.add(mnAjuda);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoPacienteActionPerformed
        
        PacienteDialog dialog = new PacienteDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        

    }//GEN-LAST:event_mniNovoPacienteActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        int opcao;
        opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(opcao);
        }
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniNovoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoMedicoActionPerformed
        MedicoDialog dialog = new MedicoDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_mniNovoMedicoActionPerformed

    private void mniPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPacientesActionPerformed
        ConsultaPacienteDialog dialog = new ConsultaPacienteDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_mniPacientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConsultaMedicoDialog dialog = new ConsultaMedicoDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mniNovaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovaConsultaActionPerformed
        
        ConsultaDialog dialog = new ConsultaDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
            
    }//GEN-LAST:event_mniNovaConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenuItem mniNovaConsulta;
    private javax.swing.JMenuItem mniNovoMedico;
    private javax.swing.JMenuItem mniNovoPaciente;
    private javax.swing.JMenuItem mniPacientes;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniSobre;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
